# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:            interp.ink
tagline:          'Interpreting between people, and grab more.'
description:      'Database Management System Developer in C/C++, sometimes uses Java/Python/C#/Javascript. Interesting in front-end framework, as well as internal system architecture and team management.'
url:              http://interp.ink

author:
  name:           'InterP'
  url:            http://interp.ink
  gravatar:       https://en.gravatar.com/yourname
  photo:          https://ko.gravatar.com/userimage/55729251/9412ef61b7ae20adcf2b9e38e49c8042.jpg?size=350
  introduction:   'Database Management System Developer in C/C++, sometimes uses Java/Python/C#/Javascript. Interesting in front-end framework, as well as internal system architecture and team management.'

paginate:         5
paginate_path:    '/blog/page:num'

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/codinfox/lanyon-codinfox.github.io
